#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
autoload -Uz promptinit
promptinit
prompt owen

export CLICOLOR=1
export LSCOLORS=gxfxcxdxbxegedabagacad

# for tab completion colors in zsh
export LS_COLORS='di=36;40:ln=35;40:so=32;40:pi=33;40:ex=31;40:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43:'
zstyle -e ':completion:*:default' list-colors 'reply=("${PREFIX:+=(#bi)($PREFIX:t)(?)*==02=01}:${(s.:.)LS_COLORS}")'

export DATA_DIR=/Users/owen_lin/repos/data/
export ROOKERY_DIR=/Users/owen_lin/repos/rookery/
export TUNGSTEN_DIR=/Users/owen_lin/repos/tungsten-support/
export OMGPRO_DIR=/Users/owen_lin/repos/omgpro/

# can also try deleting node_modules
alias jsclean="npm cache clean && rm -r ~/repos/airbnb/tmp/cache && sudo service unicorn restart && rm -r /tmp/phoenix-cache && sudo service phoenix restart"

alias sup="git fetch && git rebase origin/master && vagrant ssh -c \"'cd ~/airbnb && /usr/local/bin/owen-post-merge && sudo service unicorn restart && sudo service nginx restart'\""
alias bounce="vagrant ssh -c 'sudo service monorail restart && sudo service nginx restart'"
alias mystique="vagrant ssh -c 'sudo service monorail-mystique restart'"
alias freb="git fetch && git rebase origin/master"
alias sinstall="vagrant ssh -c \"'cd ~/airbnb && bundle install && npm install && bundle exec rake db:migrate && bundle exec rake db:test:prepare && git submodule update --init --recursive'\""
alias faster="vagrant ssh -c \"'sudo sv down bouncer-worker-0 bouncer autopricing; sudo service pricing stop; sudo service pinnacle stop; sudo service discover stop; sudo service search stop'\""
alias slower="vagrant ssh -c \"'sudo sv down bouncer-worker-0 bouncer autopricing; sudo service pricing start; sudo service pinnacle start; sudo service discover start; sudo service search start'\""
alias v="vagrant"
alias less="less -R"
alias rekey='goldkey'
alias prune='git remote prune origin'
alias undo='git reset --soft HEAD~ && git reset HEAD'
alias lerf="vagrant ssh -c \"'cd ~/repos/data/airflow/metrics_repo/deploy && ./dev_load_redis'\""
alias bluetooth="sudo kextunload -b com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport && sudo kextload -b com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport"
alias gat="ctags -R --languages=-javascript"
# alias tmuxa="tmux attach -d"
alias rc1="ssh owen_lin@rc1.musta.ch"
alias hive="ssh owen_lin@gw1.silver.musta.ch"
alias tmuxd="/bin/sh /Users/owen_lin/personal/tmux/default.sh"
alias tmuxv="/bin/sh /Users/owen_lin/personal/tmux/vagrant.sh"

export JAVA7_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home
export JAVA8_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home
export JAVA_HOME=$JAVA8_HOME

export PATH=~/bin:$JAVA_HOME/bin:/usr/local/share/python:$PATH

# Push a gem to the remote gemserver
function push-gem {
  username=`whoami`
  # resolve the DNS entry only once,
  # otherwise the commands might go to different hosts
  h=$(dig +short geminabox-internal.aws.airbnb.com|head -n1|sed s'/\.$//')
  scp $1 ${username}@${h}:~ && \
    ssh ${username}@${h} "add_gem.rb $1"
}

[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh  # This loads NVM

eval "$(rbenv init -)" # This loads rbenv

export EDITOR=vim
export VISUAL=vim
